In [28]:
import pandas as pd

In [29]:
df = pd.read_html(r"C:\Users\webde\Downloads\WV.1_Size_of_the_economy.xls")[0]
df.head()

  Unnamed: 0_level_0         Population       Surface area Population density  \
  Unnamed: 0_level_1 Unnamed: 1_level_1 Unnamed: 2_level_1 Unnamed: 3_level_1
  Unnamed: 0_level_2           millions   sq. km thousands  people per sq. km
  Unnamed: 0_level_3               2024               2024               2024
0        Afghanistan          42.647492            652.860   62.2155405301811
1            Albania           2.700000             28.750   101.375510948905
2            Algeria          46.814308           2381.741   19.0941790060296
3     American Samoa           0.046770              0.200             241.71
4            Andorra           0.081940              0.470   169.585106382979

  Gross national income, Atlas method  \
                   Unnamed: 4_level_1
                           $ billions
                                 2024
0                             15.5448
1                             23.5944
2                             249.052
3                                  ..
4                             4.00449

  Gross national income per capita, Atlas method  \
                              Unnamed: 5_level_1
                                               $
                                            2024
0                                          370.0
1                                         8690.0
2                                         5320.0
3                                             ..
4                                        48870.0

  Purchasing power parity gross national income             \
                             Unnamed: 6_level_1 per capita
                                     $ billions          $
                                           2024       2024
0                                       91.7100     2210.0
1                                       63.2759    23310.0
2                                       806.013    17220.0
3                                            ..         ..
4                                       6.40494    78170.0

  Gross domestic product
      Unnamed: 8_level_1        per capita
                % growth          % growth
                    2024              2024
0       2.26694373649188  0.10609280092082
1       3.96171911223713  5.16252191527128
2       3.29999999939609  1.86551988917833
3       1.73501577287065  3.59327606262792
4       3.37182032638998  2.00678445056737

In [30]:
if isinstance(df.columns, pd.MultiIndex):
  df.columns = ['_'.join([str(i) for i in col if str(i) !='nan']) for col in df.columns.values]

In [31]:
print(df.columns.tolist())

['Unnamed: 0_level_0_Unnamed: 0_level_1_Unnamed: 0_level_2_Unnamed: 0_level_3', 'Population_Unnamed: 1_level_1_millions_2024', 'Surface area_Unnamed: 2_level_1_sq. km thousands_2024', 'Population density_Unnamed: 3_level_1_people per sq. km_2024', 'Gross national income, Atlas method_Unnamed: 4_level_1_$ billions_2024', 'Gross national income per capita, Atlas method_Unnamed: 5_level_1_$_2024', 'Purchasing power parity gross national income_Unnamed: 6_level_1_$ billions_2024', 'Purchasing power parity gross national income_per capita_$_2024', 'Gross domestic product_Unnamed: 8_level_1_% growth_2024', 'Gross domestic product_per capita_% growth_2024']

In [32]:
renamed_df = df.rename(columns={
  'Unnamed: 0_level_0_Unnamed: 0_level_1_Unnamed: 0_level_2_Unnamed: 0_level_3': 'country',
  'Population_Unnamed: 1_level_1_millions_2024': 'population',
  'Gross national income, Atlas method_Unnamed: 4_level_1_$ billions_2024': 'GNI (billions)',
  'Purchasing power parity gross national income_Unnamed: 6_level_1_$ billions_2024': 'PPPGni (billions)',
  'Gross domestic product_Unnamed: 8_level_1_% growth_2024': 'gdp_growth_rate'
})

In [33]:
new_df = renamed_df[['country', 'population', 'GNI (billions)', 'PPPGni (billions)', 'gdp_growth_rate']].copy()
print(new_df.head())

          country  population GNI (billions) PPPGni (billions)  \
0     Afghanistan   42.647492        15.5448           91.7100
1         Albania    2.700000        23.5944           63.2759
2         Algeria   46.814308        249.052           806.013
3  American Samoa    0.046770             ..                ..
4         Andorra    0.081940        4.00449           6.40494

    gdp_growth_rate
0  2.26694373649188
1  3.96171911223713
2  3.29999999939609
3  1.73501577287065
4  3.37182032638998

In [34]:
for idx, country in new_df['country'].items():
  print(idx, country)

0 Afghanistan
1 Albania
2 Algeria
3 American Samoa
4 Andorra
5 Angola
6 Antigua and Barbuda
7 Argentina
8 Armenia
9 Aruba
10 Australia
11 Austria
12 Azerbaijan
13 Bahamas, The
14 Bahrain
15 Bangladesh
16 Barbados
17 Belarus
18 Belgium
19 Belize
20 Benin
21 Bermuda
22 Bhutan
23 Bolivia
24 Bosnia and Herzegovina
25 Botswana
26 Brazil
27 Brunei Darussalam
28 Bulgaria
29 Burkina Faso
30 Burundi
31 Cambodia
32 Cameroon
33 Canada
34 Cabo Verde
35 Cayman Islands
36 Central African Republic
37 Chad
38 Channel Islands
39 Chile
40 China
41 Hong Kong SAR, China
42 Macao SAR, China
43 Colombia
44 Comoros
45 Congo, Dem. Rep.
46 Congo, Rep.
47 Costa Rica
48 Cote d'Ivoire
49 Croatia
50 Cuba
51 Curacao
52 Cyprus
53 Czechia
54 Denmark
55 Djibouti
56 Dominica
57 Dominican Republic
58 Ecuador
59 Egypt, Arab Rep.
60 El Salvador
61 Equatorial Guinea
62 Eritrea
63 Estonia
64 Eswatini
65 Ethiopia
66 Faroe Islands
67 Fiji
68 Finland
69 France
70 French Polynesia
71 Gabon
72 Gambia, The
73 Georgia
74 Germany
75 Ghana
76 Greece
77 Greenland
78 Grenada
79 Guam
80 Guatemala
81 Guinea
82 Guinea-Bissau
83 Guyana
84 Haiti
85 Honduras
86 Hungary
87 Iceland
88 India
89 Indonesia
90 Iran, Islamic Rep.
91 Iraq
92 Ireland
93 Isle of Man
94 Israel
95 Italy
96 Jamaica
97 Japan
98 Jordan
99 Kazakhstan
100 Kenya
101 Kiribati
102 Korea, Dem. People's Rep.
103 Korea, Rep.
104 Kosovo
105 Kuwait
106 Kyrgyz Republic
107 Lao PDR
108 Latvia
109 Lebanon
110 Lesotho
111 Liberia
112 Libya
113 Liechtenstein
114 Lithuania
115 Luxembourg
116 Madagascar
117 Malawi
118 Malaysia
119 Maldives
120 Mali
121 Malta
122 Marshall Islands
123 Mauritania
124 Mauritius
125 Mexico
126 Micronesia, Fed. Sts.
127 Moldova
128 Monaco
129 Mongolia
130 Montenegro
131 Morocco
132 Mozambique
133 Myanmar
134 Namibia
135 Nauru
136 Nepal
137 Netherlands
138 New Caledonia
139 New Zealand
140 Nicaragua
141 Niger
142 Nigeria
143 North Macedonia
144 Northern Mariana Islands
145 Norway
146 Oman
147 Pakistan
148 Palau
149 Panama
150 Papua New Guinea
151 Paraguay
152 Peru
153 Philippines
154 Poland
155 Portugal
156 Puerto Rico
157 Qatar
158 Romania
159 Russian Federation
160 Rwanda
161 Samoa
162 San Marino
163 Sao Tome and Principe
164 Saudi Arabia
165 Senegal
166 Serbia
167 Seychelles
168 Sierra Leone
169 Singapore
170 Sint Maarten (Dutch part)
171 Slovak Republic
172 Slovenia
173 Solomon Islands
174 Somalia
175 South Africa
176 South Sudan
177 Spain
178 Sri Lanka
179 St. Kitts and Nevis
180 St. Lucia
181 St. Martin (French part)
182 St. Vincent and the Grenadines
183 Sudan
184 Suriname
185 Sweden
186 Switzerland
187 Syrian Arab Republic
188 Tajikistan
189 Tanzania
190 Thailand
191 Timor-Leste
192 Togo
193 Tonga
194 Trinidad and Tobago
195 Tunisia
196 Turkiye
197 Turkmenistan
198 Turks and Caicos Islands
199 Tuvalu
200 Uganda
201 Ukraine
202 United Arab Emirates
203 United Kingdom
204 United States
205 Uruguay
206 Uzbekistan
207 Vanuatu
208 Venezuela, RB
209 Viet Nam
210 Virgin Islands (U.S.)
211 West Bank and Gaza
212 Yemen, Rep.
213 Zambia
214 Zimbabwe
215 World
216 East Asia & Pacific
217 Europe & Central Asia
218 Latin America & Caribbean
219 Middle East & North Africa
220 North America
221 South Asia
222 Sub-Saharan Africa
223 Low income
224 Lower middle income
225 Upper middle income
226 High income

In [35]:
new_df = new_df.loc[0:214]
print(new_df)

                   country  population GNI (billions) PPPGni (billions)  \
0              Afghanistan   42.647492        15.5448           91.7100
1                  Albania    2.700000        23.5944           63.2759
2                  Algeria   46.814308        249.052           806.013
3           American Samoa    0.046770             ..                ..
4                  Andorra    0.081940        4.00449           6.40494
..                     ...         ...            ...               ...
210  Virgin Islands (U.S.)    0.104377             ..                ..
211     West Bank and Gaza    5.289152        16.2951           28.0705
212            Yemen, Rep.   40.583164             ..                ..
213                 Zambia   21.314956        26.9589           84.2033
214               Zimbabwe   16.634373        37.6462           64.4835

       gdp_growth_rate
0     2.26694373649188
1     3.96171911223713
2     3.29999999939609
3     1.73501577287065
4     3.37182032638998
..                 ...
210  -1.31123206333498
211  -26.5575264529877
212                 ..
213    4.0431482994443
214   2.02948414337123

[215 rows x 5 columns]

In [36]:
cols = ['population', 'GNI (billions)', 'PPPGni (billions)', 'gdp_growth_rate']
new_df[cols] = new_df[cols].apply(pd.to_numeric, errors='coerce')
print(new_df[cols])

     population  GNI (billions)  PPPGni (billions)  gdp_growth_rate
0     42.647492        15.54480           91.71000         2.266944
1      2.700000        23.59440           63.27590         3.961719
2     46.814308       249.05200          806.01300         3.300000
3      0.046770             NaN                NaN         1.735016
4      0.081940         4.00449            6.40494         3.371820
..          ...             ...                ...              ...
210    0.104377             NaN                NaN        -1.311232
211    5.289152        16.29510           28.07050       -26.557526
212   40.583164             NaN                NaN              NaN
213   21.314956        26.95890           84.20330         4.043148
214   16.634373        37.64620           64.48350         2.029484

[215 rows x 4 columns]

In [37]:
print(new_df[cols].head().round(2))

   population  GNI (billions)  PPPGni (billions)  gdp_growth_rate
0       42.65           15.54              91.71             2.27
1        2.70           23.59              63.28             3.96
2       46.81          249.05             806.01             3.30
3        0.05             NaN                NaN             1.74
4        0.08            4.00               6.40             3.37

In [38]:
print(new_df.describe())

        population  GNI (billions)  PPPGni (billions)  gdp_growth_rate
count   215.000000      200.000000         197.000000       208.000000
mean     37.760987      539.523064         978.968848         3.143646
std     143.450934     2499.951979        3701.341906         4.504077
min       0.000000        0.086041           0.081645       -26.557526
25%       0.897706       10.362725          30.127900         1.578169
50%       6.916140       38.507900          97.618900         3.268257
75%      27.118609      251.702250         535.149000         4.415530
max    1450.935791    28455.100000       37923.700000        43.372009

In [39]:
new_df['gni percapita'] = new_df['GNI (billions)'] / new_df['population']
print(new_df)

                   country  population  GNI (billions)  PPPGni (billions)  \
0              Afghanistan   42.647492        15.54480           91.71000
1                  Albania    2.700000        23.59440           63.27590
2                  Algeria   46.814308       249.05200          806.01300
3           American Samoa    0.046770             NaN                NaN
4                  Andorra    0.081940         4.00449            6.40494
..                     ...         ...             ...                ...
210  Virgin Islands (U.S.)    0.104377             NaN                NaN
211     West Bank and Gaza    5.289152        16.29510           28.07050
212            Yemen, Rep.   40.583164             NaN                NaN
213                 Zambia   21.314956        26.95890           84.20330
214               Zimbabwe   16.634373        37.64620           64.48350

     gdp_growth_rate  gni percapita
0           2.266944       0.364495
1           3.961719       8.738667
2           3.300000       5.319997
3           1.735016            NaN
4           3.371820      48.871003
..               ...            ...
210        -1.311232            NaN
211       -26.557526       3.080853
212              NaN            NaN
213         4.043148       1.264788
214         2.029484       2.263157

[215 rows x 6 columns]

In [40]:
print(new_df.nlargest(15, 'gni percapita'))

              country  population  GNI (billions)  PPPGni (billions)  \
21            Bermuda    0.064640         9.06690            8.04086
145            Norway    5.572272       547.61900          589.40700
186       Switzerland    9.000000       866.35900          820.50900
115        Luxembourg    0.700000        61.98990           72.50480
204     United States  340.110988     28455.10000        29243.10800
87            Iceland    0.400000        31.75270           31.59180
93        Isle of Man    0.084160         6.59968                NaN
92            Ireland    5.400000       419.24500          535.14900
157             Qatar    2.857822       219.24100          348.46600
169         Singapore    6.036860       451.25600          761.79900
54            Denmark    5.976992       441.05000          491.53600
66      Faroe Islands    0.054720         3.93075            4.28588
42   Macao SAR, China    0.687000        44.25140           77.03750
137       Netherlands   18.000000      1130.80000         1494.26000
10          Australia   27.204809      1701.53000         1871.75000

     gdp_growth_rate  gni percapita
21          2.105369     140.267636
145         2.100453      98.275712
186         1.302333      96.262111
115         1.031617      88.557000
204         2.796190      83.664160
87          0.516863      79.381750
93         -4.165393      78.418251
92          1.221334      77.637963
157         2.768414      76.716115
169         4.388024      74.750118
54          3.676197      73.791298
66          2.489058      71.833882
42          8.808160      64.412518
137         0.979675      62.822222
10          1.431113      62.545192

In [41]:
print(new_df.nsmallest(15, 'gni percapita'))

                      country  population  GNI (billions)  PPPGni (billions)  \
30                    Burundi   14.047790         2.71122           13.40610
0                 Afghanistan   42.647492        15.54480           91.71000
116                Madagascar   31.964956        16.42900           58.64400
36   Central African Republic    5.330690         2.74560            7.14116
117                    Malawi   21.655286        11.78930           38.84620
132                Mozambique   34.631766        18.93200           52.25630
174                   Somalia   19.009200        11.46950           30.31100
45           Congo, Dem. Rep.  109.276265        70.35700          180.61800
141                     Niger   27.032410        17.94850           53.79500
183                     Sudan   50.448963        36.15380          104.30500
187      Syrian Arab Republic   24.672760        18.23600          105.61900
111                   Liberia    5.612817         4.26893            9.86471
168              Sierra Leone    8.642022         7.25600           30.12790
29               Burkina Faso   23.548781        20.65640           65.24160
72                Gambia, The    2.759988         2.46415            9.38750

     gdp_growth_rate  gni percapita
30          3.489232       0.193000
0           2.266944       0.364495
116         4.200000       0.513969
36          1.539632       0.515055
117         1.826850       0.544407
132         1.851775       0.546666
174         3.972321       0.603366
45          6.675930       0.643845
141         8.421598       0.663962
183       -13.493292       0.716641
187        -1.207264       0.739115
111         4.792915       0.760568
168         4.000000       0.839618
29          4.985103       0.877175
72          5.746718       0.892812

In [42]:
south_asia = new_df[new_df['country'].isin(['Bangladesh', 'Bhutan', 'India', 'Maldives', 'Nepal', 'Pakistan', 'Sri Lanka'])&
                    (new_df['gni percapita'] <= 4000)]
print(south_asia)

        country   population  GNI (billions)  PPPGni (billions)  \
15   Bangladesh   173.562364       490.16400          1746.4200
22       Bhutan     0.791524         2.93788            12.0782
88        India  1450.935791      3838.58000         15956.9000
119    Maldives     0.527799         6.14843            12.4730
136       Nepal    29.651054        43.72860           172.8890
147    Pakistan   251.269164       360.17000          1541.6700
178   Sri Lanka    21.900000        84.55080           334.0700

     gdp_growth_rate  gni percapita
15          4.223259       2.824138
22          4.882594       3.711675
88          6.484224       2.645589
119         5.133962      11.649188
136         3.665374       1.474774
147         3.234784       1.433403
178         5.008719       3.860767